import 'package:flutter/material.dart';
import 'package:kbcgame/models/kbc_model.dart';

List<KbcQuiz> KbcList = <KbcQuiz>[
  KbcQuiz(
      id: 1,
      question: "Grand Central Terminal, Park Avenue, New York is the world's",
      ans: "A",
       a1: "Heighest",
       a2: "Longest",
       a3: "Nearest",
       a4: "None",
       col1: Colors.redAccent,
       col2: Colors.green

  ),
  KbcQuiz(
    id: 2,
    question: "Eritrea, which became the 182nd member of the UN in 1993, is in the continent of",
    ans: "B",
    a1: "Asia",
    a2: "Africa",
    a3: "Europe",
    a4: "Australia",
    col1: Colors.green,
    col2: Colors.indigo,
  ),
  KbcQuiz(
    id: 3,
    question: "Which country operationalized world’s largest radio telescope?",
    ans: "B",
    a1: "USA",
    a2: "China",
    a3: "Russia",
    a4: "india",
    col1: Colors.blueAccent,
    col2: Colors.purpleAccent,
  ),
  KbcQuiz(
    id: 4,
    question: "Which of the following is the capital of Arunachal Pradesh?",
    ans: "A",
    a1: "Itanagar",
    a2: "Dispur",
    a3: "Imphal",
    a4: "Panaji",
    col1: Colors.amberAccent,
    col2: Colors.deepOrangeAccent,
  ),
  KbcQuiz(
    id: 5,
    question: "Katerina Sakellaropoulou was elected the first woman President of",
    ans: "A",
    a1: "Greece",
    a2: "Spain",
    a3: "Finland",
    a4: "America",
    col1: Colors.deepPurpleAccent,
    col2: Colors.greenAccent,
  ),
  KbcQuiz(
    id: 6,
    question: "Bokaro Steel Limited was established with the assistance of",
    ans: "B",
    a1: "Germany",
    a2: "Soviet U",
    a3: "UK",
    a4: "USA",
    col1: Colors.green,
    col2: Colors.redAccent,
  ),
  KbcQuiz(
    id: 7,
    question: "In which state is the main language Khasi?",
    ans: "C",
    a1: "Mizoram",
    a2: "Nagaland",
    a3: "Meghalaya",
    a4: "Tripura",
    col1: Colors.indigo,
    col2: Colors.green,
  ),
  KbcQuiz(
    id: 8,
    question: "The head quarters of world trade organization is in",
    ans: "C",
    a1: "Montreal",
    a2: "Seattle",
    a3: "Geneva",
    a4: "the Hague",
    col1: Colors.purpleAccent,
    col2: Colors.blueAccent,
  ),
  KbcQuiz(
    id: 9,
    question: "“TB Harega Desh Jeetega” campaign aims to end Tuberculosis by the year",
    ans: "A",
    a1: "2025",
    a2: "2030",
    a3: "2035",
    a4: "2040",
    col1: Colors.deepOrangeAccent,
    col2: Colors.amberAccent,
  ),
  KbcQuiz(
    id: 10,
    question: "The 2014 football world cup is scheduled to be held in",
    ans: "D",
    a1: "China",
    a2: "Australia",
    a3: "Japan",
    a4: "Brazil",
    col1: Colors.greenAccent,
    col2: Colors.deepPurpleAccent,
  ),
];